### ISSUE TITLE
[BUG] Texts are not visible in light mode

### ISSUE THREAD

**Issue by saurabh190802** [pushkaraj2007/Rockout#12]
Texts are not visible in light mode. May be text color turning white in light mode

https://user-images.githubusercontent.com/75023861/234030641-f90aa668-776f-4465-be77-478a8c595663.mp4

**Comment by KendallDoesCoding** [comment]
@saurabh190802 - I am not facing this issue.

**Comment by saurabh190802** [comment]
> @saurabh190802 - I am not facing this issue.
@KendallDoesCoding 
Can you share some video regarding that ??
Because I am facing this on deployed site too `https://rockout.vercel.app/singleplayer`
and in home page the toggle button just making the texts invisible.

**Comment by KendallDoesCoding** [comment]
> > @saurabh190802 - I am not facing this issue.
> > @KendallDoesCoding
> > Can you share some video regarding that ??
> > Because I am facing this on deployed site too `https://rockout.vercel.app/singleplayer`
> > and in home page the toggle button just making the texts invisible.

[screen-capture (1).webm](https://user-images.githubusercontent.com/84712013/234047761-5235e90c-edc9-465f-839d-8f990fb557cd.webm)

**Comment by KendallDoesCoding** [comment]
There you go @saurabh190802 - I am not facing this issue throughout the website.

**Comment by its-your-invi** [comment]
> Texts are not visible in light mode. May be text color turning white in light mode
> 
>  2023-04-24.20-09-28.mp4

I'm also facing this issue

**Comment by gekkowrld** [comment]
> Texts are not visible in light mode. May be text color turning white in light mode
> 2023-04-24.20-09-28.mp4

Facing this issue too, maybe the text color doesn't change when switched to light mode making the text impossible to see

**Comment by pushkaraj2007** [comment]
@saurabh190802 
@KendallDoesCoding 
@its-your-invi 
@gekkowrld 

Is anyone interested in solving this issue?

**Comment by pushkaraj2007** [comment]
@saurabh190802
@KendallDoesCoding
@its-your-invi
@gekkowrld

Maybe this issue is arising is the device default is dark mode, is anyone interested in solving this issue?

**Comment by kunalshah017** [comment]
@pushkaraj2007 i would like to work on this issue please assign this to me

**Comment by KendallDoesCoding** [comment]
> @saurabh190802 @KendallDoesCoding @its-your-invi @gekkowrld
> 
> Maybe this issue is arising is the device default is dark mode, is anyone interested in solving this issue?

Makes sense. My device default is light mode, so that's why I am not facing this issue ig.

**Comment by pushkaraj2007** [comment]
@kunalshah017 

Sure, go ahead

**Comment by pushkaraj2007** [comment]
> > @saurabh190802 @KendallDoesCoding @its-your-invi @gekkowrld
> > Maybe this issue is arising is the device default is dark mode, is anyone interested in solving this issue?
> 
> Makes sense. My device default is light mode, so that's why I am not facing this issue ig.

Mine is default light mode too, that's why we are not facing this issue
