### ISSUE TITLE
[DOCS] Gameplay screenshot not working in README.md

### ISSUE THREAD

**Issue by KendallDoesCoding** [pushkaraj2007/Rockout#3]
The gameplay screenshot in README.md is not working.

**Comment by pushkaraj2007** [comment]
Do you want to work on this?

**Comment by KendallDoesCoding** [comment]
> Do you want to work on this?

Yeah. But would be great, if you would provide me with the screenshot/tell me what the screenshot must be of.

**Comment by pushkaraj2007** [comment]
The screenshot of the home page and game room will be preferable.

**Comment by KendallDoesCoding** [comment]
Hi,

I made a PR ( #7 ) please review.
