### ISSUE TITLE
[BUG] Share link (rooms) button not working.

### ISSUE THREAD

**Issue by KendallDoesCoding** [pushkaraj2007/Rockout#4]
When you create a room and tap share link, it provides the localhost:3000 link, we need to make it so that it provides the link starting with `rockout.vercel.app`.. I used the link and updated the localhost:3000 with `rockout.vercel.app` and it worked perfectly.. We just need to update it when sharing the link!

**Comment by pushkaraj2007** [comment]
@KendallDoesCoding

Thanks for raising this issue, I'm soon gonna fix this.

**Comment by pushkaraj2007** [comment]
This issue has been resolved in the 53rd commit
