### ISSUE TITLE
[FEAT] Copy the clipboard (Share rooms)

### ISSUE THREAD

**Issue by KendallDoesCoding** [pushkaraj2007/Rockout#5]
Right now, the options to share room link is only for social media.. While most people will share it on social media, some people may want to copy the link and share it using other platforms, so we should add a "Copy to clipboard" button, where the link will be copied to clipboard.

**Comment by pushkaraj2007** [comment]
@KendallDoesCoding, would you like to work on this issue?

If anyone else wants to work on it, it's also fine if @KendallDoesCoding does not want to.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding, would you like to work on this issue?
> 
> If anyone else wants to work on it, it's also fine if @KendallDoesCoding does not want to.

I don't know how I can add this functionality, so no sorry.

**Comment by saurabh190802** [comment]
@pushkaraj2007 I have fixed this. Kindly check

https://user-images.githubusercontent.com/75023861/234028047-168a6d35-82ab-45ab-9f23-861b05acc503.mp4

**Comment by pushkaraj2007** [comment]
This issue has been resolved in #11 PR
