### ISSUE TITLE
Change the How to Play section in the readme

### ISSUE THREAD

**Issue by pushkaraj2007** [pushkaraj2007/Rockout#8]
### Currently, the How to Play section in the readme looks as follows:

1. Clone the repository or download the zip file.
2. Install the necessary dependencies using npm install.
3. Run the game using npm run dev.
4. Choose the Single Player or Multiplayer mode and play the game.

These are the steps for contributing to the Game and it is for the developers, we have to change these steps according to the non-technical person who just wants to play the game and doesn't want to clone the repository, etc.

### The steps for the How to Play section should be as follows:

1. Go to [rockout.vercel.app](https://rockout.vercel.app)
2. Choose between singlePlayer and multiPlayer modes (Create a Room & Join a Room)
3. If you select singlePlayer mode, enter the number of rounds you want to play
4. If you select Create a Room, enter your name and the total number of rounds you want to play. If you select Join a Room, enter the roomId and your name.
5. Start playing the game and enjoy!

**Comment by saurabh190802** [comment]
@pushkaraj2007 I have done this. Opening a pr, Kindly check
![image](https://user-images.githubusercontent.com/75023861/233862232-c70c9041-9fe4-44d6-9456-21db59c8174c.png)
